name: suprimidospt
description: A new Flutter project.

version: 1.0.7+7

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  timeago: ^2.0.9
  firebase_messaging: ^2.1.0
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  url_launcher: ^4.0.2
  font_awesome_flutter: ^8.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png