name: suprimidospt
description: A new Flutter project.

version: 1.0.8+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0
  timeago: ^2.0.9
  firebase_messaging: ^2.1.0
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  url_launcher: ^5.0.2
  font_awesome_flutter: ^8.4.0

dev_dependencies:
  build_runner: ^1.2.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png