List locations = [
  {"key": "algarve", "value": "Algarve"},
  {"key": "aveiro", "value": "Aveiro"},
  {"key": "beiraAlta", "value": "Beira Alta"},
  {"key": "beiraBaixa", "value": "Beira Baixa"},
  {"key": "braga", "value": "Braga"},
  {"key": "casaBranca", "value": "Casa Branca"},
  {"key": "cascais", "value": "Cascais"},
  {"key": "cintura", "value": "Cintura"},
  {"key": "douro", "value": "Douro"},
  {"key": "evora", "value": "Évora"},
  {"key": "fertagus", "value": "Fertagus"},
  {"key": "guimaraes", "value": "Guimarães"},
  {"key": "minho", "value": "Minho"},
  {"key": "norte", "value": "Norte"},
  {"key": "oeste", "value": "Oeste"},
  {"key": "outros", "value": "Outros"},
  {"key": "sado", "value": "Sado"},
  {"key": "sintra", "value": "Sintra"},
  {"key": "tomar", "value": "Tomar"},
  {"key": "barreiro", "value": "Barreiro"},
  {"key": "belem", "value": "Belém"},
  {"key": "cacilhas", "value": "Cacilhas"},
  {"key": "caisDoSodre", "value": "Cais do Sodré"},
  {"key": "montijo", "value": "Montijo"},
  {"key": "brandao", "value": "Brandão"},
  {"key": "seixal", "value": "Seixal"},
  {"key": "terreiroDoPaco", "value": "Terreiro do Paço"},
  {"key": "trafaria", "value": "Trafaria"}
];

Map locationNames = {
  "algarve": "Algarve",
  "areia": "Areia",
  "aveiro": "Aveiro",
  "beiraAlta": "Beira Alta",
  "beiraBaixa": "Beira Baixa",
  "braga": "Braga",
  "carga": "Carga",
  "carvao": "Carvão",
  "casaBranca": "Casa Branca",
  "cascais": "Cascais",
  "cimento": "Cimento",
  "cintura": "Cintura",
  "douro": "Douro",
  "especial": "Especial",
  "evora": "Évora",
  "fertagus": "Fertagus",
  "guimaraes": "Guimarães",
  "madeira": "Madeira",
  "minho": "Minho",
  "norte": "Norte",
  "oeste": "Oeste",
  "sado": "Sado",
  "sintra": "Sintra",
  "soporcel": "Soporcel",
  "tomar": "Tomar",
  "barreiro": "Barreiro",
  "belem": "Belém",
  "cacilhas": "Cacilhas",
  "caisDoSodre": "Cais do Sodré",
  "montijo": "Montijo",
  "brandao": "Brandão",
  "seixal": "Seixal",
  "terreiroDoPaco": "Terreiro do Paço",
  "trafaria": "Trafaria"
};
