List locations = [
  {"key": "algarve", "value": "Algarve"},
  {"key": "areia", "value": "Areia"},
  {"key": "aveiro", "value": "Aveiro"},
  {"key": "beiraAlta", "value": "Beira Alta"},
  {"key": "beiraBaixa", "value": "Beira Baixa"},
  {"key": "braga", "value": "Braga"},
  {"key": "carga", "value": "Carga"},
  {"key": "carvao", "value": "Carvão"},
  {"key": "casaBranca", "value": "Casa Branca"},
  {"key": "cascais", "value": "Cascais"},
  {"key": "cimento", "value": "Cimento"},
  {"key": "cintura", "value": "Cintura"},
  {"key": "douro", "value": "Douro"},
  {"key": "especial", "value": "Especial"},
  {"key": "evora", "value": "Évora"},
  {"key": "fertagus", "value": "Fertagus"},
  {"key": "guimaraes", "value": "Guimarães"},
  {"key": "madeira", "value": "Madeira"},
  {"key": "minho", "value": "Minho"},
  {"key": "norte", "value": "Norte"},
  {"key": "oeste", "value": "Oeste"},
  {"key": "sado", "value": "Sado"},
  {"key": "sintra", "value": "Sintra"},
  {"key": "soporcel", "value": "Soporcel"},
  {"key": "tomar", "value": "Tomar"},
];

Map locationNames = {
  "algarve": "Algarve",
  "areia": "Areia",
  "aveiro": "Aveiro",
  "beiraAlta": "Beira Alta",
  "beiraBaixa": "Beira Baixa",
  "braga": "Braga",
  "carga": "Carga",
  "carvao": "Carvão",
  "casaBranca": "Casa Branca",
  "cascais": "Cascais",
  "cimento": "Cimento",
  "cintura": "Cintura",
  "douro": "Douro",
  "especial": "Especial",
  "evora": "Évora",
  "fertagus": "Fertagus",
  "guimaraes": "Guimarães",
  "madeira": "Madeira",
  "minho": "Minho",
  "norte": "Norte",
  "oeste": "Oeste",
  "sado": "Sado",
  "sintra": "Sintra",
  "soporcel": "Soporcel",
  "tomar": "Tomar"
};
